# Generated by Django 4.2.11 on 2024-04-19 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('address', models.CharField(db_index=True, max_length=256, verbose_name='Адрес')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('address', models.CharField(db_index=True, max_length=256, verbose_name='Адрес')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('is_provider', models.BooleanField(default=0, verbose_name='Поставщик')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
