# Generated by Django 5.0.2 on 2024-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepoint',
            name='address',
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='volume',
            field=models.FloatField(null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_provider',
            field=models.BooleanField(default=0, null=True, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='volume',
            field=models.FloatField(null=True, verbose_name='Объем'),
        ),
    ]
