# Generated by Django 5.0.2 on 2024-04-20 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_alter_salepoint_address_alter_salepoint_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associat',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.IntegerField(verbose_name='Дистанция')),
                ('duration', models.IntegerField(verbose_name='Время в секундах')),
                ('id_sale_point_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associat_rout', to='endpoint.salepoint')),
                ('id_sale_point_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.salepoint')),
                ('id_warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associat_rout', to='endpoint.warehouse')),
                ('id_warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.warehouse')),
            ],
        ),
    ]
