# Generated by Django 4.2.11 on 2024-04-19 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('coast', models.FloatField(verbose_name='Стоимость')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('product_quantity', models.IntegerField(verbose_name='Количество')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.category')),
                ('id_sale_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.salepoint')),
                ('id_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='logistics.shipment')),
                ('id_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='product.product')),
                ('id_sale_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='endpoint.salepoint')),
            ],
        ),
    ]
