# Generated by Django 4.2.11 on 2024-04-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='coast',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_cat',
            new_name='id_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_sale_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='endpoint.salepoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='endpoint.warehouse'),
        ),
    ]
