# Generated by Django 5.0.2 on 2024-04-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
        ('product', '0002_rename_coast_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_sale_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='endpoint.salepoint'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='endpoint.warehouse'),
        ),
    ]
