# Generated by Django 5.0.2 on 2024-04-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_deal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateField(),
        ),
    ]
