# Generated by Django 5.0.2 on 2024-04-20 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True)),
                ('id_sale_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='endpoint.salepoint')),
                ('id_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification', to='endpoint.warehouse')),
            ],
        ),
    ]
