# Generated by Django 4.2.11 on 2024-04-19 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('experience', models.IntegerField(default=0, verbose_name='Стаж')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_position', models.IntegerField()),
                ('complited', models.BooleanField(db_index=True, default=0, verbose_name='Состояние')),
                ('id_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_order', to='logistics.route')),
                ('id_salepoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_order', to='endpoint.salepoint')),
                ('id_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_order', to='endpoint.warehouse')),
            ],
        ),
    ]
