# Generated by Django 5.0.2 on 2024-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_driver_user_id_alter_routeorder_complited'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='volume',
            field=models.FloatField(null=True, verbose_name='Объем'),
        ),
    ]
