# Generated by Django 5.0.2 on 2024-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Назавание'),
        ),
    ]
