# Generated by Django 5.0.2 on 2024-04-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
        ('logistics', '0005_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeorder',
            name='id_salepoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_order', to='endpoint.salepoint'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='id_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_order', to='endpoint.warehouse'),
        ),
    ]
