# Generated by Django 5.0.2 on 2024-04-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_routeorder_id_salepoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.IntegerField(default=0, null=True, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='complited',
            field=models.BooleanField(default=False, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
