# Generated by Django 5.0.2 on 2024-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_driver_experience_alter_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Вес'),
        ),
    ]
